### ISSUE TITLE
Height 100%

### ISSUE THREAD

**Issue by fabrizziocht** [WebDataRocks/pivot-angular#1]
Hello, I'm Trying to use input [Height]="'100%'" with angular 6, but not works, How can I solve it?

**Comment by richierich25** [comment]
Add the below CSS to your `style.css`:
```css
html, body {
  height: 100%;
}
```
